name: Build and Deploy
on:
  push:
    branches: master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Build and Publish ${{github.repository}} to GHCR
        uses: macbre/push-to-ghcr@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          image_name: ${{ github.repository }}
          extra_args: |
            --build-arg VITE_API_URL=${{secrets.VITE_API_URL}}
            --build-arg ENVIRONTMENT=production 
